### ISSUE TITLE
support TBFC

### ISSUE THREAD

**Issue by LuoZhongYao** [cypresssemiconductorco/btstack#1]
Provide Triggered Broadcom [Bluetooth] Fast Connect support

**Comment by AnjanaMuralidharan** [comment]
Hi,

Can you please let us know which BT / combo chip are you using ?

Regards,
Anjana

**Comment by LuoZhongYao** [comment]
CYW20704 + Cotex-M4

**Comment by AnjanaMuralidharan** [comment]
Hi,

I checked internally. I am sorry, We are not supporting this feature. 

Regards,
Anjana

**Comment by LuoZhongYao** [comment]
I want to use BFC, is there any relevant documentation available?
I know that there are several BFC related HCI instructions, but there is no description of how the various parameters have been used

**Comment by AnjanaMuralidharan** [comment]
Hi, 

We do not have any fast connect option available . 
For 20704 specific queries, I would suggest you to  contact your local FAE / create a Tech Support case. 

Regards,
Anjana
